// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * The account linked to an employee, or one that could be.
 */
export type AccountSummary = { userId: number, username: string, role: Role, isActive: boolean, };
