// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day of attendance for one employee. Times are company-local `YYYY-MM-DDTHH:MM:SS`.
 */
export type AttendanceRecord = { id: number, employeeId: number, workDate: string, timeIn: string | null, timeOut: string | null, 
/**
 * PRESENT, ABSENT, ON_LEAVE, REST_DAY or HOLIDAY.
 */
status: string, lateMinutes: number, undertimeMinutes: number, workedMinutes: number, nightMinutes: number, 
/**
 * CLOCK (kiosk) or MANUAL (entered by HR).
 */
source: string, needsReview: boolean, reviewNote: string | null, 
/**
 * Inside a posted payroll period, so it can no longer change.
 */
locked: boolean, };
