// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HR adding or correcting one day. Times are `HH:MM` on the office clock; a time out
 * earlier than the time in is the next day. The reason is required and audited.
 */
export type AttendanceInput = { employeeId: number, workDate: string, timeIn: string, timeOut: string | null, reason: string, };
