// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters and page for `audit_list` and `audit_export_csv`. Dates are the office's local
 * days, inclusive at both ends.
 */
export type AuditQuery = { 
/**
 * First day, `YYYY-MM-DD`.
 */
from: string | null, 
/**
 * Last day, `YYYY-MM-DD`.
 */
to: string | null, 
/**
 * The username that did it, exactly.
 */
actor: string | null, 
/**
 * An action like `payroll.post`, or an area like `payroll.` for all of its actions.
 */
action: string | null, entityType: string | null, entityId: number | null, 
/**
 * 1-based.
 */
page: number, pageSize: number, };
