// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The values the filters can offer: everything that has ever been recorded, sorted.
 */
export type AuditFilters = { actors: Array<string>, actions: Array<string>, entityTypes: Array<string>, };
