// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded sign-in or change. `before` and `after` are what the service that made the
 * change chose to snapshot; most are small JSON objects.
 */
export type AuditEntry = { id: number, 
/**
 * UTC, like `2026-10-09T05:51:15Z`.
 */
at: string, actorUserId: number | null, actorUsername: string, action: string, entityType: string | null, entityId: number | null, before: unknown, after: unknown, };
