// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the backup history, newest first.
 */
export type BackupEntry = { id: number, 
/**
 * The full path, so Admin can find the file.
 */
path: string, sizeBytes: number, kind: "AUTO" | "MANUAL" | "PRE_RESTORE" | "PRE_POST", 
/**
 * Empty for automatic backups, which nobody started.
 */
createdByName: string | null, createdAt: string, 
/**
 * False once the file was moved or deleted, such as a manual backup on a USB drive
 * that isn't plugged in.
 */
onDisk: boolean, };
