// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HR changing one balance's yearly days, with the reason audited.
 */
export type BalanceAdjustment = { entitledHalfdays: number, reason: string, };
