// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The company as printed at the top of payslips and the payroll register.
 */
export type CompanyHeader = { 
/**
 * Empty until setup names the company.
 */
name: string, address: string, 
/**
 * Digits only, or empty.
 */
tin: string, 
/**
 * A PNG or JPEG as a `data:` URL, or nothing.
 */
logo: string | null, };
