// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Compensation = { id: number, employeeId: number, payBasis: string, rateCents: number, effectiveFrom: string, 
/**
 * Empty while this is the rate in effect now.
 */
effectiveTo: string | null, reason: string | null, 
/**
 * No tax is withheld while this rate is in effect (plan §7.5).
 */
minimumWageEarner: boolean, 
/**
 * Who made the change, or empty if that user is gone.
 */
createdByName: string | null, createdAt: string, };
