// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompensationInput = { payBasis: string, rateCents: number, effectiveFrom: string, reason: string | null, minimumWageEarner: boolean, };
