// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The semi-monthly cutoff that holds today, counted up to today.
 */
export type CutoffSummary = { periodStart: string, periodEnd: string, daysPresent: number, lateMinutes: number, 
/**
 * Approved overtime with a work date in the cutoff.
 */
overtimeMinutes: number, };
