// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A date range for listing attendance, both ends included (`YYYY-MM-DD`).
 */
export type DateRange = { from: string, to: string, };
