// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendanceRecord } from "./AttendanceRecord";

/**
 * One employee's line on HR's day grid.
 */
export type DayRow = { employeeId: number, employeeNo: string, 
/**
 * "Dela Cruz, Juan".
 */
employeeName: string, departmentName: string | null, 
/**
 * The record's status, or what the day works out to without one (ABSENT, REST_DAY,
 * HOLIDAY, ON_LEAVE). `None` when the employee has no work schedule to tell.
 */
status: string | null, 
/**
 * The holiday on this date, if any.
 */
holiday: string | null, 
/**
 * Approved leave on this date, like "Vacation Leave" or "Sick Leave (half day)".
 */
leave: string | null, record: AttendanceRecord | null, };
