// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Department = { id: number, code: string, name: string, description: string | null, isActive: boolean, };
