// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the employee list. Government IDs stay on the profile.
 */
export type EmployeeListItem = { id: number, employeeNo: string, lastName: string, firstName: string, middleName: string | null, suffix: string | null, departmentName: string | null, positionTitle: string | null, employmentStatus: string, hireDate: string, archived: boolean, };
