// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Archived } from "./Archived";
import type { EmployeeSort } from "./EmployeeSort";

/**
 * Search, filters, sort and page for `employee_list` (plan §4.6).
 */
export type EmployeeQuery = { 
/**
 * Matches employee number, first or last name, full name, or email.
 */
search: string | null, departmentId: number | null, positionId: number | null, employmentStatus: string | null, archived: Archived, sort: EmployeeSort, descending: boolean, 
/**
 * 1-based.
 */
page: number, pageSize: number, };
