// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What HR types on the employee form. Blank optional fields arrive as `null` or "".
 */
export type EmployeeInput = { employeeNo: string, firstName: string, middleName: string | null, lastName: string, suffix: string | null, birthDate: string | null, sex: string | null, civilStatus: string | null, email: string | null, mobile: string | null, address: string | null, hireDate: string, regularizationDate: string | null, separationDate: string | null, employmentStatus: string, departmentId: number | null, positionId: number | null, scheduleId: number | null, tin: string | null, sssNo: string | null, philhealthNo: string | null, pagibigNo: string | null, bankName: string | null, bankAccountNo: string | null, };
