// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeListItem } from "./EmployeeListItem";

export type EmployeePage = { items: Array<EmployeeListItem>, total: number, page: number, pageSize: number, };
