// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HolidayInput = { date: string, name: string, kind: "REGULAR" | "SPECIAL_NON_WORKING" | "SPECIAL_WORKING", };
