// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A holiday on the company calendar. A double holiday is two rows on the same date.
 */
export type Holiday = { id: number, 
/**
 * `YYYY-MM-DD`.
 */
date: string, name: string, kind: "REGULAR" | "SPECIAL_NON_WORKING" | "SPECIAL_WORKING", 
/**
 * The date is in a posted payroll period, so the holiday can't be changed.
 */
locked: boolean, };
