// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PunchKind } from "./PunchKind";

/**
 * What the kiosk shows after a punch. Only the first name, since anyone nearby can see it.
 */
export type KioskPunch = { firstName: string, kind: PunchKind, 
/**
 * The local time recorded, `YYYY-MM-DDTHH:MM:SS`.
 */
at: string, workDate: string, lateMinutes: number, };
