// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LeaveType = { id: number, code: string, name: string, isPaid: boolean, defaultHalfdaysPerYear: number, 
/**
 * Months of service before the yearly grant. SIL needs 12.
 */
minServiceMonths: number, isActive: boolean, };
