// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A leave request with what the screens show about it.
 */
export type LeaveRequest = { id: number, employeeId: number, employeeNo: string, employeeName: string, leaveTypeId: number, leaveTypeCode: string, leaveTypeName: string, isPaid: boolean, 
/**
 * `YYYY-MM-DD`, both days included.
 */
startDate: string, endDate: string, halfDay: boolean, 
/**
 * The working time it takes, in half days. Rest days and holidays off don't count.
 */
halfdays: number, reason: string, status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED", 
/**
 * The account that filed it: the employee, or HR on their behalf.
 */
filedByUsername: string | null, decidedByUsername: string | null, 
/**
 * UTC, `YYYY-MM-DDTHH:MM:SSZ`.
 */
decidedAt: string | null, decisionNote: string | null, 
/**
 * A day it covers is in a posted payroll period, so the request can't change.
 */
locked: boolean, };
