// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One employee's days of one leave type for one year.
 */
export type LeaveBalance = { id: number, employeeId: number, leaveTypeId: number, leaveTypeCode: string, leaveTypeName: string, year: number, entitledHalfdays: number, usedHalfdays: number, };
