// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filing leave. With no employee number, it's for the signed-in person.
 */
export type LeaveRequestInput = { employeeNo: string | null, leaveTypeId: number, startDate: string, endDate: string, halfDay: boolean, reason: string, };
