// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * The signed-in user, as the UI sees it.
 */
export type Me = { userId: number, username: string, role: Role, employeeId: number | null, mustChangePassword: boolean, theme: string, };
