// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutoffSummary } from "./CutoffSummary";
import type { MyDay } from "./MyDay";

/**
 * A staff member's own dashboard (plan §6.9, staff column): today, this cutoff so far,
 * and what they're still waiting on.
 */
export type MyDashboard = { today: MyDay, cutoff: CutoffSummary, 
/**
 * Their own leave requests still waiting for HR.
 */
pendingLeave: number, 
/**
 * Their own overtime requests still waiting for HR.
 */
pendingOvertime: number, };
