// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How today stands for them, the same way HR's attendance grid shows it.
 */
export type MyDay = { date: string, 
/**
 * `PRESENT`, `ABSENT`, `ON_LEAVE`, `REST_DAY` or `HOLIDAY`. `ABSENT` with no time in
 * means not clocked in yet. `None` when they have no schedule.
 */
status: string | null, timeIn: string | null, timeOut: string | null, lateMinutes: number, holiday: string | null, leave: string | null, };
