// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the signed-in employee's posted payslips, for their list.
 */
export type MyPayslip = { id: number, periodStart: string, periodEnd: string, payDate: string, grossCents: number, netCents: number, };
