// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewStaffAccount = { username: string, 
/**
 * A temporary password. The employee must replace it at first sign-in.
 */
password: string, };
