// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type NewUser = { username: string, role: Role, 
/**
 * A temporary password. The user must replace it at first sign-in.
 */
password: string, };
