// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filing overtime. Times are `HH:MM` on the office clock; an end time not after the
 * start time is the next day. With no employee number, it's for the signed-in person.
 */
export type OvertimeInput = { employeeNo: string | null, workDate: string, startTime: string, endTime: string, reason: string, };
