// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OvertimeRequest = { id: number, employeeId: number, employeeNo: string, employeeName: string, workDate: string, 
/**
 * Company-local `YYYY-MM-DDTHH:MM:SS`.
 */
startAt: string, endAt: string, minutes: number, reason: string, status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED", 
/**
 * The account that filed it: the employee, or HR on their behalf.
 */
filedByUsername: string | null, decidedByUsername: string | null, 
/**
 * UTC, `YYYY-MM-DDTHH:MM:SSZ`.
 */
decidedAt: string | null, decisionNote: string | null, 
/**
 * The date is in a posted payroll period, so the request can't change.
 */
locked: boolean, };
