// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PagIbigSettings = { 
/**
 * Monthly pay up to this uses the low rate for the employee's share.
 */
lowPayLimitCents: number, lowRateBp: number, employeeBp: number, employerBp: number, maxBaseCents: number, };
