// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayrollPeriod } from "./PayrollPeriod";
import type { RegisterRow } from "./RegisterRow";
import type { SkippedEmployee } from "./SkippedEmployee";

/**
 * A computed period: one row per payslip, plus anyone left out and why.
 */
export type PayrollRegister = { period: PayrollPeriod, rows: Array<RegisterRow>, skipped: Array<SkippedEmployee>, };
