// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Creating a period. It is named by its first day, the 1st or the 16th.
 */
export type PayrollPeriodInput = { periodStart: string, payDate: string, rulePackId: number, };
