// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayrollPeriod = { id: number, periodStart: string, periodEnd: string, payDate: string, 
/**
 * 1 for the 1st to the 15th, 2 for the 16th to the end of the month.
 */
cutoffNo: 1 | 2, status: "DRAFT" | "COMPUTED" | "APPROVED" | "POSTED", rulePackCode: string, createdByName: string | null, 
/**
 * UTC, `YYYY-MM-DDTHH:MM:SSZ`.
 */
createdAt: string, };
