// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayslipLine = { kind: "EARNING" | "DEDUCTION" | "EMPLOYER_SHARE", code: string, label: string, 
/**
 * Decimal text, such as "1.5".
 */
quantity: string, unit: "DAYS" | "HOURS" | "MINUTES" | null, 
/**
 * Deductions are negative.
 */
amountCents: number, taxable: boolean, };
