// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayslipLine } from "./PayslipLine";

/**
 * One payslip, line by line.
 */
export type PayslipDetail = { id: number, periodStart: string, periodEnd: string, payDate: string, employeeNo: string, employeeName: string, payBasis: "MONTHLY" | "DAILY", rateCents: number, lines: Array<PayslipLine>, grossCents: number, taxableCents: number, statutoryEeCents: number, taxCents: number, otherDeductionsCents: number, netCents: number, warnings: Array<string>, };
