// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PendingItem = { employeeNo: string, employeeName: string, 
/**
 * The day it is about, or the first day of a leave request.
 */
date: string, };
