// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a posted period cost the company: gross pay plus the employer's contributions.
 */
export type PeriodCost = { periodStart: string, periodEnd: string, grossCents: number, employerCents: number, costCents: number, };
