// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingItem } from "./PendingItem";

/**
 * Unfinished work inside a period that would change its payslips (plan §6.5). These are
 * warnings: HR can still create the period and sort them out before computing.
 */
export type PeriodChecks = { pendingLeave: Array<PendingItem>, pendingOvertime: Array<PendingItem>, missingTimeOuts: Array<PendingItem>, };
