// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Position = { id: number, departmentId: number, departmentName: string, title: string, 
/**
 * Monthly salary range in centavos. Outside it is a warning, never an error.
 */
minRateCents: number | null, maxRateCents: number | null, isActive: boolean, };
