// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PositionInput = { departmentId: number, title: string, minRateCents: number | null, maxRateCents: number | null, };
