// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pay for work, overtime and night hours on one kind of day, as a share of the hourly rate.
 */
export type PremiumRow = { dayType: string, workBp: number, otBp: number, nightDiffBp: number, };
