// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecurringItem = { id: number, employeeId: number, 
/**
 * ALLOWANCE, LOAN or DEDUCTION.
 */
kind: string, label: string, 
/**
 * Per cutoff it applies to.
 */
amountCents: number, taxable: boolean, 
/**
 * EVERY_CUTOFF, FIRST_CUTOFF or SECOND_CUTOFF.
 */
schedule: string, startDate: string, endDate: string | null, 
/**
 * What is still owed, for loans only.
 */
remainingBalanceCents: number | null, };
