// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecurringItemInput = { kind: string, label: string, amountCents: number, taxable: boolean, schedule: string, startDate: string, endDate: string | null, remainingBalanceCents: number | null, };
