// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterReportRow = { employeeNo: string, employeeName: string, grossCents: number, sssCents: number, philhealthCents: number, pagibigCents: number, taxCents: number, 
/**
 * Loans and other deductions.
 */
otherDeductionsCents: number, netCents: number, };
