// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterRow = { payslipId: number, employeeNo: string, employeeName: string, grossCents: number, statutoryEeCents: number, taxCents: number, otherDeductionsCents: number, netCents: number, warnings: Array<string>, };
