// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanyHeader } from "./CompanyHeader";
import type { PayrollPeriod } from "./PayrollPeriod";
import type { RegisterReportRow } from "./RegisterReportRow";

/**
 * The payroll register as a report (plan §6.8): each deduction in its own column, and a
 * totals row. Deductions are positive amounts.
 */
export type RegisterReport = { period: PayrollPeriod, company: CompanyHeader, rows: Array<RegisterReportRow>, 
/**
 * Every column added up; the name is "Total" and the number is empty.
 */
totals: RegisterReportRow, };
