// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a restore would put back, shown before Admin types RESTORE (plan §6.7).
 */
export type RestorePreview = { fileName: string, 
/**
 * When the file was last written, in UTC.
 */
savedAt: string | null, employeeCount: number, 
/**
 * The newest posted pay period's first and last day, if any.
 */
lastPostedStart: string | null, lastPostedEnd: string | null, };
