// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendanceRecord } from "./AttendanceRecord";

/**
 * A record flagged for HR, with whose it is.
 */
export type ReviewItem = { employeeNo: string, employeeName: string, record: AttendanceRecord, };
