// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who someone is in Wagecraft. Stored in `users.role` as ADMIN, HR or STAFF.
 */
export type Role = "ADMIN" | "HR" | "STAFF";
