// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PagIbigSettings } from "./PagIbigSettings";
import type { PhilHealthSettings } from "./PhilHealthSettings";

/**
 * `rule_packs.settings_json`.
 */
export type RulePackSettings = { 
/**
 * Paid days per year for a 5-day and a 6-day work week.
 */
factorFiveDay: number, factorSixDay: number, sssEmployeeBp: number, sssEmployerBp: number, philhealth: PhilHealthSettings, pagibig: PagIbigSettings, };
