// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PremiumRow } from "./PremiumRow";
import type { RulePackSettings } from "./RulePackSettings";
import type { RulePackSummary } from "./RulePackSummary";
import type { SssBracketRow } from "./SssBracketRow";
import type { TaxBracketRow } from "./TaxBracketRow";

/**
 * Everything in a rule pack, for the read-only viewer (plan §6.5). Money is in centavos
 * and rates in basis points, as stored; the screen formats them.
 */
export type RulePackDetail = { summary: RulePackSummary, settings: RulePackSettings, sssBrackets: Array<SssBracketRow>, 
/**
 * Semi-monthly brackets first, each lowest first.
 */
taxBrackets: Array<TaxBracketRow>, premiums: Array<PremiumRow>, };
