// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rule pack HR can pick for a period.
 */
export type RulePackSummary = { id: number, code: string, name: string, effectiveFrom: string, effectiveTo: string | null, };
