// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HR moving an employee to another schedule from a date.
 */
export type ScheduleChangeInput = { scheduleId: number, effectiveFrom: string, reason: string | null, };
