// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of an employee's schedule history.
 */
export type ScheduleAssignment = { id: number, scheduleId: number | null, scheduleName: string | null, 
/**
 * The schedule applies from this date until the next row's.
 */
effectiveFrom: string, reason: string | null, 
/**
 * Who made the change, or empty for the starting schedule.
 */
createdByName: string | null, };
