// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Settings screen shows.
 */
export type Settings = { companyName: string, companyAddress: string, 
/**
 * Digits only; the screen shows it grouped as 000-000-000-000.
 */
companyTin: string, 
/**
 * A PNG or JPEG as a `data:` URL. Set and removed on its own, not by saving the form.
 */
companyLogo: string | null, idleTimeoutMinutes: number, 
/**
 * Where daily backups go. Empty means the default folder.
 */
backupFolder: string, 
/**
 * The default folder, shown when `backup_folder` is empty.
 */
defaultBackupFolder: string, 
/**
 * How many daily backups to keep.
 */
backupKeep: number, };
