// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Admin saves.
 */
export type SettingsInput = { companyName: string, companyAddress: string, companyTin: string, idleTimeoutMinutes: number, backupFolder: string, backupKeep: number, };
