// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone employed during the period who has no payslip.
 */
export type SkippedEmployee = { employeeNo: string, employeeName: string, reason: string, };
