// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One SSS Monthly Salary Credit bracket. `to_cents` is inclusive; `None` on the top one.
 */
export type SssBracketRow = { fromCents: number, toCents: number | null, mscCents: number, eeCents: number, erCents: number, 
/**
 * Employees' Compensation, paid by the employer.
 */
ecCents: number, };
