// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One withholding tax bracket: tax is `base_tax` plus `rate` of the amount over `over`.
 */
export type TaxBracketRow = { frequency: "SEMI_MONTHLY" | "MONTHLY", overCents: number, notOverCents: number | null, baseTaxCents: number, rateBp: number, };
