// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepartmentCount } from "./DepartmentCount";
import type { PeriodCost } from "./PeriodCost";
import type { TodayCounts } from "./TodayCounts";

export type TeamDashboard = { 
/**
 * Employees hired by today and not separated before it.
 */
headcount: number, 
/**
 * Hired from the 1st of this month up to today.
 */
newHiresThisMonth: number, today: TodayCounts, pendingLeave: number, pendingOvertime: number, 
/**
 * Most people first; employees without a department come last.
 */
byDepartment: Array<DepartmentCount>, 
/**
 * The last six posted periods, oldest first.
 */
payrollCost: Array<PeriodCost>, };
