// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Today's attendance so far. Someone who is due today but hasn't clocked in yet counts
 * as not in, since the day isn't over.
 */
export type TodayCounts = { present: number, late: number, notIn: number, onLeave: number, };
