// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * One row of the Users screen.
 */
export type UserSummary = { id: number, username: string, role: Role, employeeId: number | null, employeeLabel: string | null, isActive: boolean, mustChangePassword: boolean, 
/**
 * True while too many wrong passwords keep the account locked.
 */
locked: boolean, lastLoginAt: string | null, };
