// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A work schedule (plan §5.3). Times are company-local `HH:MM`; an end time that is not
 * after the start time means the shift ends the next day (22:00–06:00).
 */
export type WorkSchedule = { id: number, name: string, startTime: string, endTime: string, breakMinutes: number, graceMinutes: number, 
/**
 * Comma-separated weekday codes in calendar order, like `MON,TUE,WED,THU,FRI`.
 */
workDays: string, isActive: boolean, 
/**
 * How many employees (archived ones included) are on this schedule today.
 */
employeeCount: number, };
